### ISSUE TITLE
undefined is not an object(evaluating '_graphenejsWs.Apis.instance().db_api().exec')

### ISSUE THREAD

**Issue by hzuhyb** [svk31/graphenejs-lib#10]
when i import graphenejs-lib at react-native, I get this error:
![image](https://user-images.githubusercontent.com/10185166/35261442-0fe94776-004b-11e8-89d5-67ca0a517478.png)
Environment:
OS: macOS Sierra 10.13.2
Node: 6.11.0
react-native: 0.44.3

**Comment by svk31** [comment]
There are some crypto dependencies that are not compatible with react-native, so this library as is won't work with react-native.
